creation_rules:
  - path_regex: openpgp-revocs\.d/.*\.(rev|enc\.output)$
    shamir_threshold: 2
    key_groups:
      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        age:
          - age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet

      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        age:
          - age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet

      - pgp:
          - BCE6E1D2A509156191BA016FDF0B5C535207EF1E
        age:
          - age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet

  # - path_regex: \.(yaml|yml)$
    # encrypted_regex:
    # unencrypted_regex:
    # encrypted_suffix:
    # unencrypted_suffix:
  #   pgp: >-
  #     BCE6E1D2A509156191BA016FDF0B5C535207EF1E

  # - path_regex: \.json$
  #   pgp: >-
  #     BCE6E1D2A509156191BA016FDF0B5C535207EF1E
  #   age: >-
  #     age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet
    # kms:
    # hc_vault_uris:

  # - path_regex: \.env$
  #   pgp: >-
  #     BCE6E1D2A509156191BA016FDF0B5C535207EF1E
  #   age: >-
  #     age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet
    # gcp_kms:

  # Finally, if the rules above have not matched, this one is a
  # catchall that will encrypt the file using PGP
  # The absence of a path_regex means it will match everything
  # - pgp: >-
  #     BCE6E1D2A509156191BA016FDF0B5C535207EF1E
  #   age: >-
  #     age16dzqngyqpnws7k2e4wt6ajc368qxcz6h6dhktvvlhanu38xt3sqqrjsmet
    # kms:
